### ISSUE TITLE
Not uploading images on Post Add Media 

### ISSUE THREAD

**Issue by letrape** [10up/windows-azure-storage#15]
In my wordpress site form the "Desktop" and then navigating to "Media" I can upload files to azure. 

But when I am editing a Post and try to upload an Image. The Windows shows a message saying "Uploading to Azure (1/9)"  the image appears broken and the uploaded file to Azure is 0B size and appendblob type. 

I am using the develop branch as you suggest in the support forum. Also I've change the permisions config but the issue is still happening

**Comment by RudyMartin** [comment]
I am seeing mixed results with this plugin. On some setups it works and in test and live environments it does not. TWO QUESTION: 1. Is it possible to limit the file permissions lookup to just the uploads folder? 2. Can the file upload folder be set for this module? Any help on these appreciated.

**Comment by RehanSaeed** [comment]
This PR seems to fix the issue https://github.com/10up/windows-azure-storage/pull/16 but it's been a month and it's not been looked at.

**Comment by allan23** [comment]
Hi @letrape,

Thank you for bringing this to our attention. Also, thanks to @RudyMartin for how to reproduce.

We are reviewing the PR.

**Comment by allan23** [comment]
This issue has been corrected in PR #19. The wp.org plugin repository will be updated shortly.

**Comment by RudyMartin** [comment]
Sorry, version 4.0.2 is still not working. I just updated the plugins and still getting this message:
**Windows Azure Storage requires direct filesystem access in order to work.** 

The point is that my hosting provider (pantheon) correctly blocks off write access to uploads in the plugin folders. The plugin needs to work for uploads to /wp-content/uploads folder or subfolders in this area. For this reason I am requesting the ability to change the folder(s) this module uses for uploads.

In other types of php setups you can specify 1) tmp folder, 2) public file upload folder and 3) private file upload folders as part of the configuration. 

In regard to wordpress plugin compatibility Pantheon replies on their site that:

 "Extensions that require the use of the /tmp directory are not supported. With multiple 
application servers, as exists on Live environments, it's assumed the /tmp directory will be on the 
same application container. However, as we a distributed application container matrix, 
the /tmp directory is not shared."

My suggestion is sign up for a free developer account their getpantheon.com and try the changes you just made there.

Allan, if you fix this, I believe this could truly become one of the top wordpress media management plugins. The issue really is that it fails in distributed, enterprise-type setups as it is now.

**Comment by allan23** [comment]
@RudyMartin given that your use-case is different, you can utilize the `upload_dir` filter to change the upload paths to something your hosting provider can use. I hesitate offering an option on the settings page because not every hosting provider is the same.

However, if you would like to submit a pull request as an enhancement to the settings page, please feel free to do so.

Thanks.

**Comment by pbalakri** [comment]
Please note that the situation is a prevailing best practice for security of wordpress. It would be great if there is a plugin based workaround for this.
